# Generated by Django 2.0.6 on 2018-06-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
            ],
            options={
                'verbose_name_plural': 'сумки',
                'verbose_name': 'сумка',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='виробник')),
                ('description', models.CharField(max_length=3000, verbose_name='опис')),
            ],
            options={
                'verbose_name_plural': 'виробники',
                'verbose_name': 'виробник',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='цвет')),
            ],
            options={
                'verbose_name_plural': 'кольори',
                'verbose_name': 'колір',
            },
        ),
        migrations.CreateModel(
            name='CosmeticBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
            ],
            options={
                'verbose_name_plural': 'косметички',
                'verbose_name': 'косметичка',
            },
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand', verbose_name='виробник')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Color', verbose_name='колір')),
            ],
            options={
                'verbose_name_plural': 'сукні',
                'verbose_name': 'сукня',
            },
        ),
        migrations.CreateModel(
            name='DressPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
                ('partial', models.BooleanField(default=False, verbose_name='з відрізами')),
                ('sleeve_length', models.IntegerField(blank=True, default=None, verbose_name='довжина рукава')),
                ('sleeve_width', models.IntegerField(blank=True, default=None, verbose_name='ширина рукава')),
                ('body_length', models.IntegerField(blank=True, default=None, verbose_name='довжина основи')),
                ('body_width', models.IntegerField(blank=True, default=None, verbose_name='ширина основи')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand', verbose_name='виробник')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Color', verbose_name='колір')),
            ],
            options={
                'verbose_name_plural': 'заготовки суконь',
                'verbose_name': 'заготовка сукні',
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='назва')),
                ('description', models.CharField(max_length=3000, verbose_name='опис')),
            ],
            options={
                'verbose_name_plural': 'тканини',
                'verbose_name': 'тканина',
            },
        ),
        migrations.CreateModel(
            name='Genders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='назва')),
            ],
            options={
                'verbose_name_plural': 'стать',
                'verbose_name': 'стать',
            },
        ),
        migrations.CreateModel(
            name='MobileCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
            ],
            options={
                'verbose_name_plural': 'чохли для мобільних телефонів',
                'verbose_name': 'чохол для мобільного телефону',
            },
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand', verbose_name='виробник')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Color', verbose_name='колір')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Fabric', verbose_name='тканина')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Genders', verbose_name='стать')),
            ],
            options={
                'verbose_name_plural': 'сорочки',
                'verbose_name': 'сорочка',
            },
        ),
        migrations.CreateModel(
            name='ShirtPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
                ('partial', models.BooleanField(default=False, verbose_name='з відрізами')),
                ('sleeve_length', models.IntegerField(blank=True, default=None, verbose_name='довжина рукава')),
                ('sleeve_width', models.IntegerField(blank=True, default=None, verbose_name='ширина рукава')),
                ('body_length', models.IntegerField(blank=True, default=None, verbose_name='довжина основи')),
                ('body_width', models.IntegerField(blank=True, default=None, verbose_name='ширина основи')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand', verbose_name='виробник')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Color', verbose_name='колір')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Fabric', verbose_name='тканина')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Genders', verbose_name='стать')),
            ],
            options={
                'verbose_name_plural': 'заготовки сорочок',
                'verbose_name': 'заготовка сорочки',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='размер')),
            ],
            options={
                'verbose_name_plural': 'розміри',
                'verbose_name': 'розмір',
            },
        ),
        migrations.CreateModel(
            name='Skirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand', verbose_name='виробник')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Color', verbose_name='колір')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Fabric', verbose_name='тканина')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Genders', verbose_name='стать')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Size', verbose_name='розмір')),
            ],
            options={
                'verbose_name_plural': 'спідниці',
                'verbose_name': 'спідниця',
            },
        ),
        migrations.CreateModel(
            name='SkirtPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
                ('partial', models.BooleanField(default=False, verbose_name='з відрізами')),
                ('sleeve_length', models.IntegerField(blank=True, default=None, verbose_name='довжина рукава')),
                ('sleeve_width', models.IntegerField(blank=True, default=None, verbose_name='ширина рукава')),
                ('body_length', models.IntegerField(blank=True, default=None, verbose_name='довжина основи')),
                ('body_width', models.IntegerField(blank=True, default=None, verbose_name='ширина основи')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand', verbose_name='виробник')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Color', verbose_name='колір')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Fabric', verbose_name='тканина')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Genders', verbose_name='стать')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Size', verbose_name='розмір')),
            ],
            options={
                'verbose_name_plural': 'заготовки спідниць',
                'verbose_name': 'заготовка спідниці',
            },
        ),
        migrations.CreateModel(
            name='TableCloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
            ],
            options={
                'verbose_name_plural': 'скатертини',
                'verbose_name': 'скатертина',
            },
        ),
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand', verbose_name='виробник')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Color', verbose_name='колір')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Fabric', verbose_name='тканина')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Genders', verbose_name='стать')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Size', verbose_name='розмір')),
            ],
            options={
                'verbose_name_plural': 'футболки',
                'verbose_name': 'футболка',
            },
        ),
        migrations.CreateModel(
            name='TShirtPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
                ('partial', models.BooleanField(default=False, verbose_name='з відрізами')),
                ('sleeve_length', models.IntegerField(blank=True, default=None, verbose_name='довжина рукава')),
                ('sleeve_width', models.IntegerField(blank=True, default=None, verbose_name='ширина рукава')),
                ('body_length', models.IntegerField(blank=True, default=None, verbose_name='довжина основи')),
                ('body_width', models.IntegerField(blank=True, default=None, verbose_name='ширина основи')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand', verbose_name='виробник')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Color', verbose_name='колір')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Fabric', verbose_name='тканина')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Genders', verbose_name='стать')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Size', verbose_name='розмір')),
            ],
            options={
                'verbose_name_plural': 'заготовки футболок',
                'verbose_name': 'заготовка футболки',
            },
        ),
        migrations.CreateModel(
            name='Tunic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand', verbose_name='виробник')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Color', verbose_name='колір')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Fabric', verbose_name='тканина')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Genders', verbose_name='стать')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Size', verbose_name='розмір')),
            ],
            options={
                'verbose_name_plural': 'туніки',
                'verbose_name': 'туніка',
            },
        ),
        migrations.CreateModel(
            name='TunicPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, default=None, upload_to='', verbose_name='основне фото')),
                ('price', models.IntegerField(blank=True, default=None, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
                ('partial', models.BooleanField(default=False, verbose_name='з відрізами')),
                ('sleeve_length', models.IntegerField(blank=True, default=None, verbose_name='довжина рукава')),
                ('sleeve_width', models.IntegerField(blank=True, default=None, verbose_name='ширина рукава')),
                ('body_length', models.IntegerField(blank=True, default=None, verbose_name='довжина основи')),
                ('body_width', models.IntegerField(blank=True, default=None, verbose_name='ширина основи')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand', verbose_name='виробник')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Color', verbose_name='колір')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Fabric', verbose_name='тканина')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Genders', verbose_name='стать')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Size', verbose_name='розмір')),
            ],
            options={
                'verbose_name_plural': 'заготовки тунік',
                'verbose_name': 'заготовка туніки',
            },
        ),
        migrations.AddField(
            model_name='shirtpattern',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Size', verbose_name='розмір'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Size', verbose_name='розмір'),
        ),
        migrations.AddField(
            model_name='dresspattern',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Fabric', verbose_name='тканина'),
        ),
        migrations.AddField(
            model_name='dresspattern',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Genders', verbose_name='стать'),
        ),
        migrations.AddField(
            model_name='dresspattern',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Size', verbose_name='розмір'),
        ),
        migrations.AddField(
            model_name='dress',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Fabric', verbose_name='тканина'),
        ),
        migrations.AddField(
            model_name='dress',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Genders', verbose_name='стать'),
        ),
        migrations.AddField(
            model_name='dress',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Size', verbose_name='розмір'),
        ),
    ]
