# Generated by Django 3.0.1 on 2019-12-20 11:23

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='назва відділу')),
                ('code_name', models.CharField(default=None, max_length=100, verbose_name='програмна назва')),
                ('notes', models.TextField(blank=True, default=None, max_length=2000, verbose_name='примітки')),
                ('slug', models.SlugField(blank=True, default=None, max_length=30, null=True, verbose_name='URL в адресній стрічці броузера')),
            ],
            options={
                'verbose_name': 'відділ магазину',
                'verbose_name_plural': 'відділи магазину',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='опис')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('slug', models.SlugField(blank=True, default=None, max_length=30, null=True, verbose_name='URL в адресній стрічці броузера')),
                ('pseudo_deleted', models.BooleanField(default=False, verbose_name='видалений')),
                ('available_sizes', models.ManyToManyField(to='properties.Size', verbose_name='доступні розміри')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.Brand', verbose_name='виробник')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.Color', verbose_name='колір')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.Fabric', verbose_name='тканина')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='назва')),
                ('code_name', models.CharField(default=None, max_length=100, verbose_name='програмна назва')),
                ('notes', models.TextField(blank=True, default=None, max_length=2000, verbose_name='примітки')),
                ('slug', models.SlugField(blank=True, default=None, max_length=30, null=True, verbose_name='URL в адресній стрічці броузера')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=product.models.get_section_upload_path, verbose_name='зображення секції')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Department', verbose_name='відділ магазину')),
            ],
            options={
                'verbose_name': 'секція відділу магазину',
                'verbose_name_plural': 'секції відділів магазину',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='назва типу товару')),
                ('name_plural', models.CharField(default=None, max_length=100, verbose_name='назва типу товару у множині')),
                ('code_name', models.CharField(default=None, max_length=100, verbose_name='програмна назва')),
                ('notes', models.TextField(blank=True, default=None, max_length=2000, verbose_name='примітки')),
                ('slug', models.SlugField(blank=True, default=None, max_length=30, null=True, verbose_name='URL в адресній стрічці броузера')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=product.models.get_item_upload_path, verbose_name='зображення секції')),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to=product.models.get_item_upload_path, verbose_name='іконка секції')),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Section', verbose_name='секція магазину')),
            ],
            options={
                'verbose_name': 'тип товару',
                'verbose_name_plural': 'типи товарів',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=False, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to=product.models.get_upload_path, verbose_name='фото товару')),
                ('item_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Item', verbose_name='для товару')),
            ],
            options={
                'verbose_name': 'Зображення товару',
                'verbose_name_plural': 'Зображення товарів',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.ItemType', verbose_name='тип товару'),
        ),
    ]
