# Generated by Django 2.0.6 on 2018-06-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/bag_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CosmeticBagImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/cosmetic_bag_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DressImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/dress_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DressPatternImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/dress_pattern_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MobileCaseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/mobile_case_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShirtImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/shirt_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShirtPatternImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/shirt_pattern_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkirtImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/skirt_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkirtPatternImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/skirt_pattern_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TableClothImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/table_cloth_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TShirtImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/tshirt_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TShirtPatternImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/tshirt_pattern_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TunicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/tunic_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TunicPatternImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=True, verbose_name='основне фото')),
                ('image', models.ImageField(blank=True, default=None, upload_to='item_images/tunic_pattern_images', verbose_name='фото товару')),
            ],
            options={
                'verbose_name_plural': 'зображення товарів',
                'verbose_name': 'зображення товару',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bag',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cosmeticbag',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dress',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dresspattern',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mobilecase',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shirtpattern',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skirt',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skirtpattern',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tablecloth',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tshirtpattern',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tunic',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tunicpattern',
            name='image',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
        migrations.AddField(
            model_name='tunicpatternimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TunicPattern', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='tunicimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Tunic', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='tshirtpatternimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TShirtPattern', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='tshirtimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Shirt', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='tableclothimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TableCloth', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='skirtpatternimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SkirtPattern', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='skirtimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Skirt', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='shirtpatternimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ShirtPattern', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='shirtimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Shirt', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='mobilecaseimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.MobileCase', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='dresspatternimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.DressPattern', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='dressimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Dress', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='cosmeticbagimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.CosmeticBag', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='bagimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Bag', verbose_name='товар'),
        ),
    ]
