# Generated by Django 2.0.6 on 2018-06-24 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180624_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirtimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.TShirt', verbose_name='товар'),
        ),
    ]
