# Generated by Django 2.0.6 on 2018-06-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180624_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='cosmeticbagimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='dressimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='dresspatternimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='mobilecaseimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='shirtimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='shirtpatternimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='skirtimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='skirtpatternimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='tableclothimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='tshirtimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='tshirtpatternimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='tunicimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
        migrations.AlterField(
            model_name='tunicpatternimage',
            name='is_basic',
            field=models.BooleanField(default=False, verbose_name='основне фото'),
        ),
    ]
