# Generated by Django 2.0.6 on 2018-06-25 17:24

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180624_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='cosmeticbagimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='dressimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='dresspatternimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='mobilecaseimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='shirtimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='shirtpatternimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='skirtimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='skirtpatternimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='tableclothimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='tshirtimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='tshirtpatternimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='tunicimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AddField(
            model_name='tunicpatternimage',
            name='code',
            field=models.PositiveIntegerField(default=1, verbose_name='код товару'),
        ),
        migrations.AlterField(
            model_name='shirtimage',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=product.models.get_upload_path, verbose_name='фото товару'),
        ),
    ]
