# Generated by Django 2.0.6 on 2018-07-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20180626_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cosmeticbagimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='dressimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='dresspatternimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='mobilecaseimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='shirtimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='shirtpatternimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='skirtimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='skirtpatternimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='tableclothimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='tshirtimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='tshirtpatternimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='tunicimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='tunicpatternimage',
            name='item',
        ),
        migrations.DeleteModel(
            name='BagImage',
        ),
        migrations.DeleteModel(
            name='CosmeticBagImage',
        ),
        migrations.DeleteModel(
            name='DressImage',
        ),
        migrations.DeleteModel(
            name='DressPatternImage',
        ),
        migrations.DeleteModel(
            name='MobileCaseImage',
        ),
        migrations.DeleteModel(
            name='ShirtImage',
        ),
        migrations.DeleteModel(
            name='ShirtPatternImage',
        ),
        migrations.DeleteModel(
            name='SkirtImage',
        ),
        migrations.DeleteModel(
            name='SkirtPatternImage',
        ),
        migrations.DeleteModel(
            name='TableClothImage',
        ),
        migrations.DeleteModel(
            name='TShirtImage',
        ),
        migrations.DeleteModel(
            name='TShirtPatternImage',
        ),
        migrations.DeleteModel(
            name='TunicImage',
        ),
        migrations.DeleteModel(
            name='TunicPatternImage',
        ),
    ]
