# Generated by Django 2.0.6 on 2018-07-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('product', '0007_auto_20180702_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('object_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name='показувати')),
                ('is_basic', models.BooleanField(default=False, verbose_name='основне фото')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Зображення товару',
                'verbose_name_plural': 'Зображення товарів',
            },
        ),
    ]
