# Generated by Django 2.0.6 on 2018-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_itemimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='cosmeticbag',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='dresspattern',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='mobilecase',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='shirtpattern',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='skirt',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='skirtpattern',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='tablecloth',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='tshirtpattern',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='tunic',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='tunicpattern',
            name='description',
            field=models.TextField(default=None, max_length=3000, verbose_name='опис'),
        ),
    ]
