# Generated by Django 2.0.6 on 2018-08-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20180803_1123'),
        ('product', '0011_auto_20180704_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='назва відділу')),
                ('code_name', models.CharField(default=None, max_length=100, verbose_name='програмна назва')),
                ('notes', models.TextField(blank=True, default=None, max_length=2000, verbose_name='примітки')),
            ],
            options={
                'verbose_name': 'відділ магазину',
                'verbose_name_plural': 'відділи магазину',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(blank=True, default=None, editable=False, unique=True, verbose_name='код')),
                ('name', models.CharField(blank=True, default=None, max_length=40, verbose_name='найменування')),
                ('description', models.TextField(default=None, max_length=3000, verbose_name='опис')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, verbose_name='ціна')),
                ('available', models.BooleanField(default=False, verbose_name='у продажі')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='додано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('item_code', models.CharField(blank=True, default=None, max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.Brand', verbose_name='виробник')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.Color', verbose_name='колір')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.Fabric', verbose_name='тканина')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.Gender', verbose_name='стать')),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='назва типу товару')),
                ('name_plural', models.CharField(default=None, max_length=100, verbose_name='назва типу товару у множині')),
                ('code_name', models.CharField(default=None, max_length=100, verbose_name='програмна назва')),
                ('notes', models.TextField(blank=True, default=None, max_length=2000, verbose_name='примітки')),
            ],
            options={
                'verbose_name': 'тип товару',
                'verbose_name_plural': 'типи товарів',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='назва')),
                ('code_name', models.CharField(default=None, max_length=100, verbose_name='програмна назва')),
                ('notes', models.TextField(blank=True, default=None, max_length=2000, verbose_name='примітки')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Department', verbose_name='відділ магазину')),
            ],
            options={
                'verbose_name': 'секція відділу магазину',
                'verbose_name_plural': 'секції відділів магазину',
            },
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
        migrations.DeleteModel(
            name='CosmeticBag',
        ),
        migrations.RemoveField(
            model_name='dress',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='dress',
            name='color',
        ),
        migrations.RemoveField(
            model_name='dress',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='dress',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='dress',
            name='size',
        ),
        migrations.RemoveField(
            model_name='dresspattern',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='dresspattern',
            name='color',
        ),
        migrations.RemoveField(
            model_name='dresspattern',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='dresspattern',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='dresspattern',
            name='size',
        ),
        migrations.DeleteModel(
            name='MobileCase',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='size',
        ),
        migrations.RemoveField(
            model_name='shirtpattern',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='shirtpattern',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shirtpattern',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='shirtpattern',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='shirtpattern',
            name='size',
        ),
        migrations.RemoveField(
            model_name='skirt',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='skirt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='skirt',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='skirt',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='skirt',
            name='size',
        ),
        migrations.RemoveField(
            model_name='skirtpattern',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='skirtpattern',
            name='color',
        ),
        migrations.RemoveField(
            model_name='skirtpattern',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='skirtpattern',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='skirtpattern',
            name='size',
        ),
        migrations.DeleteModel(
            name='TableCloth',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tshirt',
            name='size',
        ),
        migrations.RemoveField(
            model_name='tshirtpattern',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='tshirtpattern',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tshirtpattern',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='tshirtpattern',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tshirtpattern',
            name='size',
        ),
        migrations.RemoveField(
            model_name='tunic',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='tunic',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tunic',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='tunic',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tunic',
            name='size',
        ),
        migrations.RemoveField(
            model_name='tunicpattern',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='tunicpattern',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tunicpattern',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='tunicpattern',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tunicpattern',
            name='size',
        ),
        migrations.DeleteModel(
            name='Dress',
        ),
        migrations.DeleteModel(
            name='DressPattern',
        ),
        migrations.DeleteModel(
            name='Shirt',
        ),
        migrations.DeleteModel(
            name='ShirtPattern',
        ),
        migrations.DeleteModel(
            name='Skirt',
        ),
        migrations.DeleteModel(
            name='SkirtPattern',
        ),
        migrations.DeleteModel(
            name='TShirt',
        ),
        migrations.DeleteModel(
            name='TShirtPattern',
        ),
        migrations.DeleteModel(
            name='Tunic',
        ),
        migrations.DeleteModel(
            name='TunicPattern',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Section', verbose_name='секція магазину'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.ItemType', verbose_name='тип товару'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.Size', verbose_name='розмір'),
        ),
    ]
