# Generated by Django 2.0.6 on 2018-09-11 07:05

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='icon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=product.models.get_item_upload_path, verbose_name='іконка секції'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=product.models.get_item_upload_path, verbose_name='зображення секції'),
        ),
    ]
