# Generated by Django 2.0.6 on 2019-01-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20180911_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='size_height',
            field=models.CharField(choices=[('0', 'універсальний'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='size_width',
            field=models.CharField(choices=[('0', 'універсальний'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60')], default='0', max_length=20),
        ),
    ]
