# Generated by Django 2.0.6 on 2019-01-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20180921_0622'),
        ('product', '0019_auto_20190102_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.AddField(
            model_name='item',
            name='available_sizes',
            field=models.ManyToManyField(to='properties.Size', verbose_name='доступні розміри'),
        ),
    ]
