# Generated by Django 2.0.6 on 2019-09-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20190102_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gender',
        ),
    ]
