# Generated by Django 2.0.5 on 2019-09-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_item_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='код'),
        ),
    ]
