# Generated by Django 2.0.5 on 2019-09-19 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20190912_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='object_id',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='item_related',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Item', verbose_name='для товару'),
            preserve_default=False,
        ),
    ]
