# Generated by Django 2.0.5 on 2019-11-11 11:07

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20190919_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(default=None, upload_to=product.models.get_upload_path, verbose_name='фото товару'),
        ),
    ]
