# Generated by Django 2.0.5 on 2019-11-11 12:06

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20191111_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=product.models.get_upload_path, verbose_name='фото товару'),
        ),
    ]
