# Generated by Django 2.0.5 on 2019-12-12 09:20

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20191111_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(default=False, upload_to=product.models.get_upload_path, verbose_name='фото товару'),
        ),
    ]
