# Generated by Django 2.0.6 on 2019-12-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20191212_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pseudo_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
