# Generated by Django 2.0.6 on 2018-06-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='виробник')),
                ('description', models.CharField(max_length=3000, verbose_name='опис')),
            ],
            options={
                'verbose_name': 'виробник',
                'verbose_name_plural': 'виробники',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'колір',
                'verbose_name_plural': 'кольори',
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='назва')),
                ('description', models.CharField(max_length=3000, verbose_name='опис')),
            ],
            options={
                'verbose_name': 'тканина',
                'verbose_name_plural': 'тканини',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='назва')),
            ],
            options={
                'verbose_name': 'стать',
                'verbose_name_plural': 'стать',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='размер')),
            ],
            options={
                'verbose_name': 'розмір',
                'verbose_name_plural': 'розміри',
            },
        ),
    ]
