# Generated by Django 3.0.1 on 2019-12-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='виробник')),
                ('description', models.TextField(max_length=30000, verbose_name='опис')),
                ('slug', models.SlugField(blank=True, default=None, max_length=30, null=True, verbose_name='URL в адресній стрічці броузера')),
            ],
            options={
                'verbose_name': 'виробник',
                'verbose_name_plural': 'виробники',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='колір')),
                ('slug', models.SlugField(blank=True, default=None, max_length=30, null=True, verbose_name='URL в адресній стрічці броузера')),
            ],
            options={
                'verbose_name': 'колір',
                'verbose_name_plural': 'кольори',
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='назва')),
                ('description', models.TextField(max_length=30000, verbose_name='опис')),
                ('slug', models.SlugField(blank=True, default=None, max_length=30, null=True, verbose_name='URL в адресній стрічці броузера')),
            ],
            options={
                'verbose_name': 'тканина',
                'verbose_name_plural': 'тканини',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='розмір')),
                ('slug', models.SlugField(blank=True, default=None, max_length=30, null=True, verbose_name='URL в адресній стрічці броузера')),
            ],
            options={
                'verbose_name': 'розмір',
                'verbose_name_plural': 'розміри',
            },
        ),
    ]
