# Generated by Django 2.0.6 on 2019-09-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20180921_0622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
