# Generated by Django 3.0.1 on 2019-12-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('session_key', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Ключ сесії покупця')),
                ('total_basket_price', models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=10, null=True, verbose_name='Загальна ціна корзини')),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Список корзин',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Назва')),
                ('description', models.TextField(max_length=300, null=True, verbose_name='Опис')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступність')),
            ],
            options={
                'verbose_name': 'Спосіб доставки',
                'verbose_name_plural': 'Способи доставки',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, null=True, verbose_name='Програмна назва')),
                ('verbose_name', models.CharField(default=None, max_length=64, null=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Опис')),
                ('number', models.PositiveSmallIntegerField(blank=True, default=True, null=True, verbose_name='Порядковий номер')),
            ],
            options={
                'verbose_name': 'Статус замовлення',
                'verbose_name_plural': 'Статуси замовлень',
            },
        ),
        migrations.CreateModel(
            name='ProductInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Одиниць')),
                ('one_product_price', models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=10, null=True, verbose_name='Ціна за одну одиницю')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=10, null=True, verbose_name='Загальна ціна по товару')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('session_key', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('basket', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Basket', verbose_name='Корзина')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Item', verbose_name='Товар')),
                ('size', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.Size', verbose_name='Розмір')),
            ],
            options={
                'verbose_name': 'Замовлений товар у корзині',
                'verbose_name_plural': 'Замовлені товари у корзині',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('code', models.PositiveSmallIntegerField(blank=True, default=None, editable=False, null=True, verbose_name='Код')),
                ('hash_code', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='хеш-код')),
                ('session_key', models.CharField(max_length=128, null=True, verbose_name='Ключ сесії покупця')),
                ('customer_name', models.CharField(default=None, max_length=80, null=True, verbose_name="Ім'я покупця")),
                ('customer_email', models.EmailField(default=None, max_length=70, null=True, verbose_name='Електронна пошта покупця')),
                ('customer_phone', models.CharField(default=None, max_length=40, null=True, verbose_name='Телефон покупця')),
                ('customer_comment', models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Комментар до замовлення')),
                ('customer_city', models.CharField(default=None, max_length=80, null=True, verbose_name='Місто покупця')),
                ('customer_address', models.CharField(default=None, max_length=100, null=True, verbose_name='Адреса (вулиця, будинок) покупця')),
                ('postal_code', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Поштовий код')),
                ('manager_comment', models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Примітки')),
                ('is_removed', models.BooleanField(default=False, verbose_name='Видалене')),
                ('delivery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.DeliveryMethod', verbose_name='Спосіб доставки')),
                ('status', models.ManyToManyField(blank=True, default=None, to='orders.Status', verbose_name='Статус замовлення')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='order',
            field=models.OneToOneField(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Належність до замовлення'),
        ),
    ]
