# Generated by Django 2.0.7 on 2018-07-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180703_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='order',
        ),
    ]
