# Generated by Django 2.0.7 on 2018-07-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180703_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='one_product_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='ціна за одну одиницю'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='загальна ціна по товару'),
        ),
    ]
