# Generated by Django 2.0.6 on 2018-07-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180704_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Загальна ціна замовлення'),
        ),
    ]
