# Generated by Django 2.0.6 on 2018-07-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180705_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='one_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='ціна за одну одиницю'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='загальна ціна по товару'),
        ),
    ]
