# Generated by Django 2.0.6 on 2018-07-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180710_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=10, null=True, verbose_name='Загальна ціна замовлення'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='one_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=10, null=True, verbose_name='ціна за одну одиницю'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=10, null=True, verbose_name='загальна ціна по товару'),
        ),
    ]
