# Generated by Django 2.0.6 on 2018-07-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180710_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=64, verbose_name="Ім'я покупця"),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Тип товару'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='ID товару'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='one_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=10, null=True, verbose_name='Ціна за одну одиницю'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Одиниць'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=10, null=True, verbose_name='Загальна ціна по товару'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='Назва статуса'),
        ),
    ]
