# Generated by Django 2.0.6 on 2018-07-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180710_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Товар відмінено'),
        ),
    ]
