# Generated by Django 2.0.6 on 2018-08-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20180716_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_comment',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Примітки'),
        ),
    ]
