# Generated by Django 2.0.6 on 2018-08-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_manager_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_new',
            field=models.BooleanField(default=True, editable=False, verbose_name='Нове'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_opened',
            field=models.BooleanField(default=False, editable=False, verbose_name='Відкрито'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, editable=False, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_received',
            field=models.BooleanField(default=False, editable=False, verbose_name='Отримано'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(default=False, editable=False, verbose_name='Відправлено'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_verified',
            field=models.BooleanField(default=False, editable=False, verbose_name='Перевірено'),
        ),
        migrations.AddField(
            model_name='status',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='status',
            name='verbose_name',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='Програмна назва'),
        ),
    ]
