# Generated by Django 2.0.6 on 2018-12-21 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0016_order_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID товару')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Одиниць')),
                ('one_product_price', models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=10, null=True, verbose_name='Ціна за одну одиницю')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=10, null=True, verbose_name='Загальна ціна по товару')),
                ('is_inactive', models.BooleanField(default=False, verbose_name='Товар відмінено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Тип товару')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name_plural': 'Замовлені товари у корзині',
                'verbose_name': 'Замовлений товар у корзині',
            },
        ),
    ]
