# Generated by Django 2.0.6 on 2018-12-22 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20180911_1005'),
        ('orders', '0018_productinbasket_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='object_id',
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Item', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Item', verbose_name='Товар'),
        ),
    ]
