# Generated by Django 2.0.6 on 2019-01-02 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20180921_0622'),
        ('orders', '0021_remove_productinbasket_is_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='size',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.Size', verbose_name='Розмір'),
        ),
    ]
