# Generated by Django 2.0.6 on 2019-01-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_productinbasket_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('session_key', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Ключ сесії покупця')),
                ('total_basket_price', models.DecimalField(blank=True, decimal_places=2, default=None, editable=False, max_digits=10, null=True, verbose_name='Загальна ціна корзини')),
                ('is_closed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.Order', verbose_name='Належність до замовлення')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Список корзин',
            },
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductInOrder',
        ),
    ]
