# Generated by Django 2.0.6 on 2019-01-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20190119_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.PositiveSmallIntegerField(blank=True, default=None, editable=False, null=True, verbose_name='Код'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
