# Generated by Django 2.0.6 on 2019-01-21 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20190119_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Назва')),
                ('description', models.TextField(max_length=300, null=True, verbose_name='Опис')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступність')),
            ],
            options={
                'verbose_name': 'Спосіб доставки',
                'verbose_name_plural': 'Способи доставки',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Адреса (вулиця, будинок) покупця'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_city',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Місто покупця'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.PositiveSmallIntegerField(blank=True, default=None, max_length=20, null=True, verbose_name='Поштовий код'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, default=None, max_length=30, null=True, verbose_name='Електронна пошта покупця'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_opened',
            field=models.BooleanField(default=False, editable=False, verbose_name='Прочитано менеджером'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено замовником'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name='Отримано замовником'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Відправлено до замовника'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Інформацію перевірено та підтверджено менеджером'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.DeliveryMethod', verbose_name='Спосіб доставки'),
        ),
    ]
