# Generated by Django 2.0.6 on 2019-01-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20190121_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Поштовий код'),
        ),
    ]
