# Generated by Django 2.0.6 on 2019-01-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20190128_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Ключ сесії покупця'),
        ),
    ]
