# Generated by Django 2.0.6 on 2019-01-31 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20190131_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, null=True, verbose_name='Програмна назва')),
                ('verbose_name', models.CharField(default=None, max_length=64, null=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Статус замовлення',
                'verbose_name_plural': 'Статуси замовлень',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_opened',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Status', verbose_name='Статус замовлення'),
        ),
    ]
