# Generated by Django 2.0.6 on 2019-01-29 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_order_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='order',
            field=models.OneToOneField(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Належність до замовлення'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='basket',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Basket', verbose_name='Корзина'),
        ),
    ]
