# Generated by Django 2.0.6 on 2019-01-29 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20190129_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='basket',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Basket', verbose_name='Корзина'),
        ),
    ]
