# Generated by Django 2.0.6 on 2019-02-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20190129_0430'),
        ('orders', '0033_auto_20190131_1252'),
    ]

    operations = [
    ]
