# Generated by Django 2.0.6 on 2019-02-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_merge_20190207_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hash_code',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True, verbose_name='хеш-код'),
        ),
    ]
