# Generated by Django 2.0.6 on 2019-02-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_status_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='orders.Status', verbose_name='Статус замовлення'),
        ),
    ]
