# Generated by Django 2.0.6 on 2019-03-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20190306_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(max_length=100, null=True, verbose_name='Адреса (вулиця, будинок) покупця'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_city',
            field=models.CharField(max_length=80, null=True, verbose_name='Місто покупця'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(max_length=70, null=True, verbose_name='Електронна пошта покупця'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=80, verbose_name="Ім'я покупця"),
        ),
    ]
