# Generated by Django 2.0.5 on 2019-10-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_auto_20190902_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='orders.Status', verbose_name='Статус замовлення'),
        ),
    ]
