# Generated by Django 2.0.5 on 2019-11-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_auto_20191007_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ManyToManyField(blank=True, default=None, to='orders.Status', verbose_name='Статус замовлення'),
        ),
    ]
